# Generated by Django 4.1.6 on 2023-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('title', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(default=None, upload_to='images/')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
